kind: pipeline
name: default
type: docker

when:
  branch:
  - master
  event:
    exclude:
    - pull_request

steps:
- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.71.0
    pull: always
    url: https://mnavarro.dev
    validate: true
    config: config.yaml

- name: deploy
  image: appleboy/drone-scp
  settings:
    host: 95.179.203.51
    target:
      from_secret: ssh_target
    source: public/*
    username:
      from_secret: ssh_user
    key:
      from_secret: ssh_key
    port:
      from_secret: ssh_port