version: '3.7'

services:
    # This service runs the dev server in hugo
    dev-server:
        image: klakegg/hugo:latest-ext
        container_name: blog-hugo-dev-server
        volumes:
            - .:/src
        ports:
            - 1313:1313
        command: server -D -F -E --enableGitInfo
