baseURL: "https://mnavarro.dev/"
languageCode: "en-GB"
title: "mnavarro.dev"
metaDataFormat: "yaml"

pygmentsUseClassic: true
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentOptions: "linenos=inline"

disqusShortname: "mnavarro"
googleAnalytics: "UA-73118336-11"

Params:
  mainSections: ["post","posts"]
  dateFormat: "2 January 2006"
  rss: true
  comments: true
  readingTime: true
  wordCount: true
  socialShare: true
  delayDisqus: true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
  Edit:
    repo: "https://git.mnavarro.dev/mnavarro/blog"
    branch: "master"
  Social:
    name: "Matías Navarro Carter"
    website: "mnavarro.dev"
    email: "mnavarrocarter@gmail.com"
    github: "mnavarrocarter"
    gitlab: "mnavarrocarter"
    twitter: "mnavarrocarter"
    linkedin: "mnavarrocarter"
    stackoverflow: "users/7379050/matías-navarro-carter"
    instagram: "mnavarrocarter"
    youtube: "channel/UCsdipFUfs6gcj1rQKEIlWLg" 
    telegram: "mnavarrocarter"

menu:
  main:
  - name: "Blog"
    url: ""
    weight: 1
  - name: "About"
    url: "/about"
    weight: 2
  - name: "Media"
    url: "/media"
    weight: 3