baseurl = "https://mnavarro.dev/"
languageCode = "en-GB"
metaDataFormat = "yaml"
DefaultContentLanguage = "en"
theme = "terminal"
paginate = 5

[params]
contentTypeName = "posts"
themeColor = "blue"
showLanguageSelector = true
showMenuItems = 3
fullWidthTheme = false
centerTheme = true
disqus = "mnavarro"

[params.twitter]
creator = "mnavarrocarter"
site = "mnavarrocarter"

[author]
name = "Matias Navarro-Carter"
homepage = "https://twitter.com/mnavarrocarter"

[languages.en]
contentDir = "content/en"
languageName = "English"
weight = 1
title = "The Chilean Nerd"
subtitle = "I sound like I'm angry all the time, but I'm a very nice guy. I promise."
keywords = "chilean,blog,programming,matias,navarro,carter,php,programming,golang"
copyright = "©2019 Matias Navarro Carter. CC-BY-SA."
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"

[languages.es]
contentDir = "content/es"
languageName = "Español"
weight = 2
title = "El Chileno Nerd"
subtitle = "A veces sueno medio enojado, pero soy super simpático. En serio."
keywords = "chileno,nerd,blog,matias,navarro,carter,php,programacion,golang"
copyright = "©2019 Matias Navarro Carter. CC-BY-SA."
menuMore = "Ver más"
readMore = "Leer más"
readOtherPosts = "Leer otros artículos"

[languages.en.params.logo]
logoText = "The Chilean Nerd"
logoHomeLink = "/"

[languages.es.params.logo]
logoText = "El Chileno Nerd"
logoHomeLink = "/"

[[languages.en.menu.main]]
weight = 0
identifier = "about"
name = "About"
url = "/about"
[[languages.en.menu.main]]
weight = 1
identifier = "showcase"
name = "Showcase"
url = "/showcase"
[[languages.en.menu.main]]
weight = 2
identifier = "github"
name = "Github"
url = "https://github.com/mnavarrocarter"

[[languages.es.menu.main]]
weight = 0
idestifier = "sobremi"
name = "Sobre Mi"
url = "/es/sobre-mi"
[[languages.es.menu.main]]
weight = 1
identifier = "vitrina"
name = "Vitrina"
url = "/es/vitrina"
[[languages.es.menu.main]]
weight = 2
identifier = "github"
name = "Github"
url = "https://github.com/mnavarrocarter"