name: Deployment
on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/web:${{ github.sha }}
      
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@master
    
    - name: Checkout submodules
      shell: bash
      run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      
    - name: Login docker
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        TOKEN: ${{ github.token }}
      run: docker login docker.pkg.github.com -u $USERNAME -p $TOKEN
    
    - name: Build Image
      run: docker build . --tag $IMAGE_NAME
    
    - name: Pubblish Image
      run: docker push $IMAGE_NAME
    
    - name: Deploy to Kubernetes
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image --record deployment/blog blog=$IMAGE_NAME
