name: Deployment
on:
  push:
    branches:
      - master
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@master
    
    - name: Build & Publish to Registry
      uses: jerray/publish-docker-action@master
      with:
        repository: ${{ github.repository }}/hugo
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        tags: latest,${{ github.sha }}
    
    - name: Deploy to Kubernetes
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image --record deployment/blog container=${{ github.repository }}:${{ github.sha }}
